version: '3.8'

services:
  db:
    image: mysql:8.0
    # load DB_PASSWORD / DB_NAME from .env.staging
    env_file:
      - .env.staging
    environment:
      # now populated from DB_PASSWORD / DB_NAME
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE:       ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    restart: always

  backend:
    image: mahditalaldev/nextstep:latest
    ports:
      - "3000:3000"
    # load all your app vars
    env_file:
      - .env.staging
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  mysql_data:
