# services:
#   backend:
#     image: mahditalaldev/nextstep-backend:latest
#     ports:
#       - "3000:3000"
#     environment:
#       - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/nextstep
#       - NODE_ENV=production
#       - JWT_SECRET=${JWT_SECRET}
#       - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
#       - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
#     depends_on:
#       - db
#     restart: always

#   db:
#     image: mysql:8.0
#     ports:
#       - "3306:3306"
#     environment:
#       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#       - MYSQL_DATABASE=nextstep
      
#     volumes:
#       - mysql_data:/var/lib/mysql
#     restart: always
#     command: --default-authentication-plugin=mysql_native_password

# volumes:
#   mysql_data: 

services:
  backend:
    image: mahditalaldev/nextstep:latest
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=your_secret_here
      - JWT_EXPIRES_IN=1h
      - GOOGLE_CLIENT_ID=your_client_id_here
      - GOOGLE_CLIENT_SECRET=your_client_secret_here
      - CORS_ORIGIN=http://15.236.226.177:3000
      - OPENAI_API_KEY=your_openai_api_key_here
      - N8N_WEBHOOK_Test_URL=your_n8n_webhook_test_url_here
      - N8N_WEBHOOK_URL=your_n8n_webhook_url_here
      - DATABASE_URL=url
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: 