name: Push and Run Backend

on:
  push:
    branches:
      - staging
jobs:

  Build-Backend-And-Push-Dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Build Docker image
        run: docker build -f ./Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/nextstep-backend:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nextstep-backend:latest

  Deploy-to-EC2:
    needs: Build-Backend-And-Push-Dockerhub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
        uses: actions/checkout@v3
    - name: Copy docker-compose to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "docker-compose.yaml"
          target: "/home/${{ secrets.EC2_USER }}/"


