name: Push and Run Backend

on:
  push:
    branches:
      - staging
jobs:

  Build-Backend-And-Push-Dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Build Docker image
        run: docker build -f ./Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/nextstep-backend:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nextstep-backend:latest
