name: Deploy to Staging

on:
  push:
    branches:
      - MT-staging

jobs:
  Build-Frontend-And-Upload-S3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Configure .env for Staging
        working-directory: frontend
        run: |
          sed -i "s|VITE_API_URL=.*|VITE_API_URL=http://${{ secrets.EC2_HOST_STAGING }}:3000|g" .env.example
          cp .env.example .env

      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Copy Frontend Build to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "frontend/dist"
          target: "/home/${{ secrets.EC2_USER }}/frontend/dist"

      - name: Upload Build to S3
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p ~/.aws
            echo "[default]" > ~/.aws/config
            echo "region = ${{ secrets.AWS_DEFAULT_REGION }}" >> ~/.aws/config
            aws s3 cp ~/frontend/dist/ s3://fse-final-mahdi --recursive
            rm -rf ~/frontend/dist
