name: deploy to staging

on:
  push:
    branches:
      - MT-staging

jobs:
  Build-and-Push-Backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & push backend image
        working-directory: backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nextstep:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/nextstep:latest

  Build-Frontend-And-Upload-S3:
    runs-on: ubuntu-latest
    needs: Build-and-Push-Backend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Inject API URL into frontend .env
        working-directory: frontend
        run: |
          sed -i "s|VITE_API_URL=.*|VITE_API_URL=http://${{ secrets.EC2_HOST_STAGING }}:3000|g" .env.example
          cp .env.example .env

      - run: npm install
        working-directory: frontend

      - run: npm run build
        working-directory: frontend

      - name: Copy build to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "frontend/dist"
          target: "/home/${{ secrets.EC2_USER }}/frontend/dist"

      - name: Deploy build to S3
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p ~/.aws
            echo "[default]" > ~/.aws/config
            echo "region = ${{ secrets.AWS_DEFAULT_REGION }}" >> ~/.aws/config
            aws s3 cp ~/frontend/dist/ s3://fse-final-mahdi --recursive
            rm -rf ~/frontend/dist

  Deploy-With-Compose:
    runs-on: ubuntu-latest
    needs:
      - Build-and-Push-Backend
      - Build-Frontend-And-Upload-S3
    steps:
      - uses: actions/checkout@v3

      - name: Copy compose + env to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: |
            - docker-compose.staging.yml
            - .env.staging
          target: "/home/${{ secrets.EC2_USER }}"

      - name: Deploy on EC2 via Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~
            docker compose -f docker-compose.staging.yml pull
            docker compose -f docker-compose.staging.yml down
            docker compose -f docker-compose.staging.yml up -d
